### PR TITLE
Swap nica fork for libnica submodule, update stamps (fixed)

### PR DESCRIPTION
**Pull request by ikeydoherty**
Keeping our own private fork of libnica has been a complete pain to maintain for the longest time.
Thus, we drop the fork, and make use of nica's submodule support.

In addition, we update the copyright range to include this year.

In theory this will also help with coverage by restricting it to CBM itself.

Note: Had to redo the PR as I used the wrong nica url (ssh not https, so it would only work for me :P)

### CODE REVIEW

**Comment by ikeydoherty** [comment]
Yo Travis, 1999 called, wants its toolchain back.

**Comment by ikeydoherty** [comment]
@travis: https://www.youtube.com/watch?v=pNfDUUMGRCo

**Comment by bryteise** [comment]
Looks good, poor coverage =(.

**Comment by ikeydoherty** [comment]
Yeah poor thing :( But in a sense this is good, because Nica was masking the issue of poor coverage by making it seem not as bad as it was :)

**Pull request merged**
