### PR TITLE
Remove OpenSSL & Cleanup Code

### PR DESCRIPTION
**Pull request by ikeydoherty**
Removing OpenSSL completely to avoid the upcoming ABI break, using a very simple `mmap` based `memcmp` buffer comparison.

Also fixed several issues in the code to remove potential bugs.

### CODE REVIEW

**Comment by ikeydoherty** [comment]
Shut up coveralls, its 63% locally.

**Comment by ikeydoherty** [comment]
@bryteise might wanna give this the once over :)

**Comment by ikeydoherty** [comment]
Closing as I need to add more changes ...

**Comment by bryteise** [comment]
Alrighty, I'll be on the lookout. Mind adding a change to the file descriptor leak detection while you are in there similar to https://github.com/clearlinux/swupd-client/commit/f071915dcb4867b934bd9bfc4472d8de8701b566?

**Comment by ikeydoherty** [comment]
@ahkok did that one a while back in e02efe4fa3adcb95a7d2f6a8e73619058da75da3

**Comment by ikeydoherty** [comment]
I opened a new PR btw over at #23

**Pull request closed without merging**
