### PR TITLE
Travis GCC5/C11

### PR DESCRIPTION
**Pull request by ikeydoherty**
- Switch tree to using GCC 5 (vs GCC 4.8.0 ...)
 - Include updated Nica which has switched to C11
 - Enable C11 by default
 - Fix derp in makefile
 - Underp ordering of travis dependencies

### CODE REVIEW

**Comment by ikeydoherty** [comment]
Shut up coveralls, nothing changed.

**Comment by ikeydoherty** [comment]
Local coverage report:

```
Writing directory view page.
Overall coverage rate:
  lines......: 65.7% (1046 of 1591 lines)
  functions..: 79.2% (84 of 106 functions)
```

**Comment by ikeydoherty** [comment]
(TBF I'm using GCC 6.3.0 locally so it seems we have coverage numbers all over the place.)

**Comment by bryteise** [comment]
Coverage numbers everywhere =/.

**Comment by ikeydoherty** [comment]
It's brutal :'( I'll rebase my initrd branch, and make sure that my new coverage is higher than my locally recorded `65.7%`. Meaning that it HAS to raise on the initrd inclusion...

Cheers for merging, sorry for making CBM so prominent in your life lately xD

**Pull request merged**
